version: '2.4'
services:
  client:
    image: curlimages/curl:7.84.0
    command: "curl -XGET http://front-svc:8090/greet"
    depends_on:
      front-svc:
        condition: service_healthy
      back-svc:
        condition: service_healthy
      jaeger:
        condition: service_started
      prometheus:
        condition: service_started
      otel-collector:
        condition: service_started
  
  front-svc:
    build:
      # we set the build context to github.com/riandyrn/otelchi because we use relative 
      # path in go.mod for otelchi library
      context: ../../

      # since we are now on github.com/riandyrn/otelchi, the dockerfile location would be
      # in ./examples/multi-services/front-svc/Dockerfile
      dockerfile: ./examples/multi-services/front-svc/Dockerfile
    healthcheck:
      test: "curl -XGET http://localhost:8090"
      start_period: 5s
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      - BACK_SERVICE_URL=http://back-svc:8091
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318/v1/metrics
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/v1/traces
    ports:
      - 8090:8090
  
  back-svc:
    build:
      # we set the build context to github.com/riandyrn/otelchi because we use relative 
      # path in go.mod for otelchi library
      context: ../../

      # since we are now on github.com/riandyrn/otelchi, the dockerfile location would be
      # in ./examples/multi-services/back-svc/Dockerfile
      dockerfile: ./examples/multi-services/back-svc/Dockerfile
    healthcheck:
      test: "curl -XGET http://localhost:8091"
      start_period: 5s
    depends_on:
      otel-collector:
        condition: service_started
    environment:
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_EXPORTER_OTLP_METRICS_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_METRICS_ENDPOINT=http://otel-collector:4318/v1/metrics
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://otel-collector:4318/v1/traces
    ports:
      - 8091:8091
  
  otel-collector:
    # otel-collector to collect all our monitoring data
    image: otel/opentelemetry-collector-contrib:0.115.1
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "8888:8888"   # metrics endpoint
      - "8889:8889"   # Prometheus exporter
    logging:
      driver: "none"
  
  jaeger:
    image: jaegertracing/all-in-one:1.56
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    ports:
      - 16686:16686 # for serving jaeger front-end
      - 6831:6831/udp # for jaeger-agent UDP
    logging:
      driver: none # intentionally turnoff the logging so it doesn't clutter the terminal
  
  prometheus:
    # prometheus to collect all our metrics
    image: prom/prometheus:v3.0.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    logging:
      driver: "none"
