global:
  # check on our services every 15 seconds
  scrape_interval: 15s
  # how often we should check if anything's wrong
  evaluation_interval: 15s

scrape_configs:
  # get metrics from our collector
  # it's already done all the hard work of gathering everything
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    # only grab metrics with 'otelchi'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '.*otelchi.*'
        action: keep
